version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    # - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    # - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    # - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    # - testpackage
    # - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    # - wsl
    - zerologlint

  settings:
    varnamelen:
      ignore-decls:
        - wg *sync.WaitGroup
        - mu *sync.Mutex
        - b backoff.BackOffContext
        - b backoff.BackOff
    revive:
      rules:
        - name: unused-parameter
          exclude:
          - func(t *testing.T) testCase {

  exclusions:
    rules:
      - path: .*_test.go
        text: net/http.Get must not be called
      - path: .*_test.go
        linters:
          - lll
          - funlen
          - gosec
          - exhaustruct
          - maintidx
          - varnamelen
          - errcheck
      - path: .*_test.go
        linters:
          - revive
        text: "unused-parameter: parameter 't' seems to be unused, consider removing or renaming it as _"

formatters:
  enable:
    - gci
    - gofmt
    - goimports
    - gofumpt

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kiteggrad)
        - localmodule
        - blank
        - dot