// Code generated by mockery. DO NOT EDIT.

package tcontainer_mocks

import (
	tcontainer "github.com/kiteggrad/tcontainer"
	mock "github.com/stretchr/testify/mock"
)

// BuildOption is an autogenerated mock type for the BuildOption type
type BuildOption struct {
	mock.Mock
}

type BuildOption_Expecter struct {
	mock *mock.Mock
}

func (_m *BuildOption) EXPECT() *BuildOption_Expecter {
	return &BuildOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: options
func (_m *BuildOption) Execute(options *tcontainer.BuildOptions) error {
	ret := _m.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*tcontainer.BuildOptions) error); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BuildOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type BuildOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - options *tcontainer.BuildOptions
func (_e *BuildOption_Expecter) Execute(options interface{}) *BuildOption_Execute_Call {
	return &BuildOption_Execute_Call{Call: _e.mock.On("Execute", options)}
}

func (_c *BuildOption_Execute_Call) Run(run func(options *tcontainer.BuildOptions)) *BuildOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*tcontainer.BuildOptions))
	})
	return _c
}

func (_c *BuildOption_Execute_Call) Return(err error) *BuildOption_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BuildOption_Execute_Call) RunAndReturn(run func(*tcontainer.BuildOptions) error) *BuildOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewBuildOption creates a new instance of BuildOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuildOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuildOption {
	mock := &BuildOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
